---
- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: delete default vhost
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: ensure nginx content directory is created
  file: path=/usr/share/mysite state=directory

- name: copy index.html
  template: src=index.html.j2 dest=/usr/share/mysite/index.html
  
- name: add nginx vhost
  action: template src=nginx-host.j2 dest=/etc/nginx/sites-available/my-site
  notify:
    - restart nginx

- name: link nginx vhost in sites-enabled
  action: file src=/etc/nginx/sites-available/my-site dest=/etc/nginx/sites-enabled/my-site state=link
  notify:
    - restart nginx
    
    
    
